// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_tech.Context;

#nullable disable

namespace api_tech.Migrations
{
    [DbContext(typeof(lojaContext))]
    partial class lojaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api_tech.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Item_Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Produto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("api_tech.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Dt_venda")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("produtoId")
                        .HasColumnType("int");

                    b.Property<int?>("vendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("produtoId");

                    b.HasIndex("vendedorId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("api_tech.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendedors");
                });

            modelBuilder.Entity("api_tech.Models.Venda", b =>
                {
                    b.HasOne("api_tech.Models.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produtoId");

                    b.HasOne("api_tech.Models.Vendedor", "vendedor")
                        .WithMany()
                        .HasForeignKey("vendedorId");

                    b.Navigation("produto");

                    b.Navigation("vendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
